# rozelle-scaffold: example exercise.
#
# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/
#

message = """
Can you write some Python code to say hello to Alice, Bob, Carol, \
and David with a for loop and only one print statement?
"""

expected_output = """
Hello, Alice!
Hello, Bob!
Hello, Carol!
Hello, Dave!
"""

[[constraints]]
description = "You cannot use the `print` function more than once."
on = "function"
match = "print"
limits = { max = 1 }

[[constraints]]
description = "You cannot use more than one `for` loop."
on = "node"
match = "For"
limits = { min = 1 }
